# Uncomment the next line to define a global platform for your project
platform :osx, '10.9'

target 'URLog' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for URLog
  pod 'Magnet'

  target 'URLogTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'URLogUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
